# Generated by Django 4.1.7 on 2023-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('image', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Фото товара')),
                ('category', models.CharField(choices=[('milk', 'Молоко'), ('juice', 'Соки'), ('meat', 'Мясо'), ('other', 'Разное')], default='other', max_length=20, verbose_name='Категория')),
                ('remains', models.PositiveIntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
        ),
    ]
